# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Martin
middle_name:
last_name: Carrasco
email: martin.carrascocastaneda@unifr.ch
description: >
  Welcome :)
keywords: martin carrasco, geometric deep learning, topological deep learning, topological data analysis
lang: en
icon: ⚛️

url: https://martin-carrasco.github.io/
baseurl: /
last_updated: false

# -----------------------------------------------------------------------------
# Social
# -----------------------------------------------------------------------------

bluesky_url: martinca.bsky.social
github_username: martin-carrasco
linkedin_username: "martin-carrasco-6456a5195/"
orcid_id: 0000-0003-3420-8048
scholar_userid: CfMrnMoAAAAJ
x_username: "@Martin19194054"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - scripts/
  - vendor

keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-sitemap

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

# -----------------------------------------------------------------------------
# Sitemap defaults
# -----------------------------------------------------------------------------

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
